### ISSUE TITLE
Installed but cant execute

### ISSUE THREAD

**Issue by hanswayne23** [evzpav/run-freqtrade-docker#1]
I followed all installation still cant execute?
sudo apt update

sudo apt-get install apt-transport-https ca-certificates curl gnupg software-
properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
 $(lsb_release -cs) stable"

sudo apt install docker-ce

sudo systemctl status docker

docker -v

apt install make

git clone github.com/evzpav/run-freqtrade-docker

cd run-freqtrade-docker

make init

Adjust and add Telegram and Exchange API keys to ~/.freqtrade/config_dry.json and ~/.freqtrade/config_prod.json newly created

make run-backtest \
    STRATEGY=BBRSI \
    CONFIG_FILE=config_dry.json \
    DB_FILE=tradesv3.dryrun.sqlite

ron@ronvb:~/run-freqtrade-docker$ make run-backtest \
>     STRATEGY=BBRSI \
>     CONFIG_FILE=config_dry.json \
>     DB_FILE=tradesv3.dryrun.sqlite
make run \
PARAMS='backtesting --refresh-pairs-cached'
make[1]: Entering directory '/home/mtg/run-freqtrade-docker'
docker run \
	--rm \
	--name freqtrade \
	-v /etc/timezone:/etc/timezone:ro \
 	-v ~/.freqtrade/config_dry.json:/freqtrade/config.json \
	-v ~/.freqtrade/tradesv3.dryrun.sqlite:/freqtrade/tradesv3.dryrun.sqlite \
	-v /home/ron/run-freqtrade-docker/strategies:/freqtrade/user_data/strategies \
	-it freqtradeorg/freqtrade:latest \
	--db-url sqlite:///tradesv3.dryrun.sqlite \
	--strategy=BBRSI \
	backtesting --refresh-pairs-cached
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/create?name=freqtrade: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
Makefile:12: recipe for target 'run' failed
make[1]: *** [run] Error 126
make[1]: Leaving directory '/home/ron/run-freqtrade-docker'
Makefile:30: recipe for target 'run-backtest' failed
make: *** [run-backtest] Error 2

My apology im newbie with algorithmic trading and freqtrade.

Kindly need help on this one...

Thanks.

**Comment by evzpav** [comment]
Hello, you have to be able to run docker as non-root user. Follow instructions here: https://docs.docker.com/install/linux/linux-postinstall/
